name: Deploy Frontend to Vercel

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'next.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'tailwind.config.js'
      - '.env*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      
      # Verify pnpm installation
      - name: Check pnpm version
        run: pnpm --version

      # Install frontend dependencies
      - name: Install dependencies
        run: pnpm install

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      # Build the Next.js application
      - name: Build project
        run: pnpm build

      # Deploy to Vercel (without project and org IDs)
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm