name: Deploy Frontend to Vercel

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'next.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
      - 'tailwind.config.js'
      - '.env*'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.x
      
      - name: Check pnpm version
        run: pnpm --version

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
